version: "3"
services:

  frontend:
    image: sajalkhan/mern_contact_manager:frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mern-network
    volumes:
      - /frontend/node_modules
    depends_on:
      - backend
    environment:
      - BACKEND=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true
  
  backend:
    image: sajalkhan/mern_contact_manager:backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - mern-network
    volumes:
      - ./backend/src:/usr/app/src
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017
      - FRONTEND=http://localhost:3000
      - SUPPRESS_NO_CONFIG_WARNING = true

  db:
    image: mongo:3.6.19-xenial
    ports:
      - 27017:27017
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
