
export const SEARCH_CONTACT  = 'SEARCH_CONTACT';
export const ADD_NEW_CONTACT = 'ADD_NEW_CONTACT';
export const DELETE_CONTACT  = 'DELETE_CONTACT';
export const ERROR_MESSAGE   = 'ERROR_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const GET_ALL_CONTACT = 'GET_ALL_CONTACT';