name: Integration

on:
  push:
    branches:
      - master
      - "feat/*"
    paths-ignore: 
      - 'coverage/**'
      - 'dist/**'
      - 'docs/**'

jobs:
  # check build is successful
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from (master)
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: "npm"
      
      - name: 'Npm install and build'
          run: |
            cd backend
            npm install
            npm run build
            cd ..
            cd frontend
            npm install
            npm run build

  check_merge_conflict:
    runs-on: ubuntu-latest
    name: Find merge conflicts
    steps:
      - name: Checkout from (master)
        uses: actions/checkout@v2
      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v4.0
