name: Integration

on:
  push:
    branches:
      - master
      - "feat/*"
    paths-ignore: 
      - 'coverage/**'
      - 'dist/**'
      - 'docs/**'

  pull_request:
    branches:
      - master
      - 'feat/*'

jobs:
  # check build is successful
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from (master)
        uses: actions/checkout@v2
      - name: Node Setup frontend
        run: |
          npm i
          npm run build
        working-directory: frontend

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from (master)
        uses: actions/checkout@v2
      - name: Node Setup backend
        run: |
          npm i
        working-directory: backend
