name: Release

on:
  push:
    branches: [main]

jobs:
  # check deploy successful
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from (master)
        uses: actions/checkout@v2
      
