name: Release

on:
  push:
    branches: [master]

jobs:
  # check deploy successful
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from (master)
        uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the docker-image
        run: docker-compose -f docker-compose-dev.yml up -d
      
      - name: Docker push
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/mern_contact_manager
      
