name: Release

on:
  push:
    branches: [master]

jobs:
  # check deploy successful
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from (master)
        uses: actions/checkout@v2
      - name: Docker login
        env:
          NAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $NAME -p $PASSWORD
      
      - name: Docker push
        run: docker-compose push
      
